algo = input('Digite algo: ')
print('O tipo do que foi digitado é ', type(algo))
print('O que foi digitado é alfanumérico? ->', algo.isalnum())
print('O que foi digitado é alfabético? ->', algo.isalpha())
print('O que foi digitado é ASCII? ->', algo.isascii())
print('O que foi digitado é numérico? ->', algo.isdigit())
print('O que foi digitado é minúsculo? ->', algo.islower())
